### ISSUE TITLE
Support splitting yaml into multiple files

### ISSUE THREAD

**Issue by spyglass-software** [spyglasshq/spyglass-cli#23]
This will help organize as files can get quite large.

**Comment by APTy** [comment]
Example file structure we'd like to support:

```
/spyglass

  /roles
    /team
      team_sales.yml
      team_engineering.yml
      ...

    /service_roles
      svc_observability.yml
      svc_data_pipelines.yml
      svc_dashboards.yml
      ...

  /users
    /service_users
      svc_observability.yml
      svc_data_pipelines.yml
      svc_dashboards.yml
      ...

    /people
      tyler@spyglass.software.yml
      nick@spyglass.software.yml
      ...

  /warehouses
    compute_wh.yml
    default_svc_wh.yml
    dashboards_wh.yml
    ...

  spyglass.yml
```

**Comment by spyglass-software** [comment]
The read path is pretty simple, crawl the directory for all `*.{yaml,yml}` files and combine them into one super-object in memory.

There are two write important write paths: `import` and `sync`.

### Import

For import, we will by default write to a single file. However, it's clear that some users will want a structure like "one file per role, one file per user, etc.". Rather than require users to have to split up the files themselves, we should provide some light tooling to help with this.

Maybe we give a script template for splitting a yaml file into sub-files, and let users customize it as needed. But until we know more about what are the preferred structures, it's probably too premature too provide a flag like `import --split-files` to do it all automatically.

### Sync

Sync reads all the files into a single yaml object in memory, updates that object based on Snowflake config, and then writes back to the files. To accomplish this, we'll need to basically iterate over all the files and update them in-place, only replacing the relevant parts of files that have been changed.

If there are new roles that have been introduced, we'll probably put it in some kind of top-level `uncategorized.yaml` or similar (this is where having a configured "splitting policy" might help, because then we'd know how to categorize new entities.
